[[constraint]]
  name = "github.com/drone/drone-go"
  revision = "eaa41f7836a191224ec5702d2458db07882ec269"

[[constraint]]
  name = "github.com/drone-plugins/drone-git-push"
  version = "0.1.0"

[prune]
  go-tests = true
  unused-packages = true
